language: node_js
sudo: false

env:
  - SENECA_VER=@3.x.x
  
node_js:
  - '8'

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
  - npm uninstall seneca
  - npm install seneca$SENECA_VER
  - psql -U postgres -f docker/dbschema.sql

after_script:
  - npm run coveralls
